### PR TITLE
Error messages

### PR DESCRIPTION
**Pull request by johenglisch**
People came to me asking for help with some errors but the errors were so low-level that I had to dive into the source code to find out what *actually* went wrong.

So I thought it might be a good idea to add a few human-friendly error messages here and there:

 * Complain about misspelt dataset ids on the cli instead of silently ignoring them
 * Complain about malformed tsv files (empty rows, trailing columns, that sort of thing)

(also, since I was touching the code anyways, I updated the ci configs, too)

### CODE REVIEW

**Review by xrotwang — APPROVED** [review]
We can drop py3.7 from the github action as well. Other than that looks good.

**Review by LinguList — APPROVED** [review]
:-) Looks nice to me ! Thanks!

**Review by AnnikaTjuka — APPROVED** [review]
Super, many thanks! This will make it much easier to spot these tiny errors that are not immediately visible.

**Comment by johenglisch** [comment]
>We can drop py3.7 from the github action as well

Ah, I missed that one, thanks.  Done.

So, all that's needed now is to approve the ci changes and merge the branch (I don't have write access in the *concepticon* org).

**Comment by xrotwang** [comment]
Do we need a new release - or are people installing from source?

**Comment by johenglisch** [comment]
>Do we need a new release - or are people installing from source?

I don't know for sure but the the data repo [recommends to *pip install* it](https://github.com/concepticon/norare-data?tab=readme-ov-file#install-pynorare), so I suspect that's what people do.

**Comment by AnnikaTjuka** [comment]
Yes, I would also prefer a minor release. I have a new student assistant adding data to NoRaRe and it would be a nice example to show how package updates work.

**Comment by xrotwang** [comment]
ok, will do

**Comment by AnnikaTjuka** [comment]
Many thanks!

**Comment by xrotwang** [comment]
https://pypi.org/project/pynorare/1.1.0/

**Pull request merged**
